version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - docker-rails-sample-db-volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3002:3000"
    depends_on:
      - db

volumes:
  docker-rails-sample-db-volumes: